# Project: Project3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main2.o 2.o
LINKOBJ  = main2.o 2.o
LIBS     = -L"D:/Applications/C/Dev-Cpp/MinGW64/lib" -L"D:/Applications/C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/Applications/C/Dev-Cpp/MinGW64/include" -I"D:/Applications/C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Applications/C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Applications/C/Dev-Cpp/MinGW64/include" -I"D:/Applications/C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Applications/C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Applications/C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project2.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main2.o: main2.cpp
	$(CPP) -c main2.cpp -o main2.o $(CXXFLAGS)

2.o: 2.cpp
	$(CPP) -c 2.cpp -o 2.o $(CXXFLAGS)
